// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDs_joaSftQjO0xjW5Ct5P-PKi02hc68',
    appId: '1:149225066853:web:04176edc9b207019b9518c',
    messagingSenderId: '149225066853',
    projectId: 'shop-dekho',
    authDomain: 'shop-dekho.firebaseapp.com',
    storageBucket: 'shop-dekho.firebasestorage.app',
    measurementId: 'G-K7K5ZB94Z8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKIcHE_Z7FCR2Z-GkHqzwNh-No9GaAsko',
    appId: '1:149225066853:ios:dbcc2d9a6fd2bfd1b9518c',
    messagingSenderId: '149225066853',
    projectId: 'shop-dekho',
    storageBucket: 'shop-dekho.firebasestorage.app',
    iosClientId: '149225066853-umoailhv4mble48i9hng9lk6p9loojq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopdekhoCustomer',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKIcHE_Z7FCR2Z-GkHqzwNh-No9GaAsko',
    appId: '1:149225066853:ios:dbcc2d9a6fd2bfd1b9518c',
    messagingSenderId: '149225066853',
    projectId: 'shop-dekho',
    storageBucket: 'shop-dekho.firebasestorage.app',
    iosClientId: '149225066853-umoailhv4mble48i9hng9lk6p9loojq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopdekhoCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxDs_joaSftQjO0xjW5Ct5P-PKi02hc68',
    appId: '1:149225066853:web:34935807bd4cca2cb9518c',
    messagingSenderId: '149225066853',
    projectId: 'shop-dekho',
    authDomain: 'shop-dekho.firebaseapp.com',
    storageBucket: 'shop-dekho.firebasestorage.app',
    measurementId: 'G-8CHLFJVQR4',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaeU5mvsEUj4SAERwgATfuc6joNmGnK_A',
    appId: '1:149225066853:android:32f95bebe63c7f84b9518c',
    messagingSenderId: '149225066853',
    projectId: 'shop-dekho',
    storageBucket: 'shop-dekho.firebasestorage.app',
  );
}
